name: build-and-deploy

on:
  push:
    branches: [main, toofanPro2]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install and cache R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::tidyverse
            any::vtable
            any::patchwork
            any::readxl
            any::treemap

      - name: Render Quarto project
        run: quarto render .

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
